version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=jamartinluque@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - tfg-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tfg-backend
    labels:
      - "traefik.enable=true"
      # Router para la API (ya existente)
      - "traefik.http.routers.backend.rule=Host(`tfgproject.duckdns.org`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      # Router adicional para servir /uploads
      - "traefik.http.routers.backend-uploads.rule=Host(`tfgproject.duckdns.org`) && PathPrefix(`/uploads`)"
      - "traefik.http.routers.backend-uploads.entrypoints=websecure"
      - "traefik.http.routers.backend-uploads.tls.certresolver=myresolver"
      - "traefik.http.services.backend-uploads.loadbalancer.server.port=8080"
      # Router adicional para servir la consola de H2
      - "traefik.http.routers.backend-h2.rule=Host(`tfgproject.duckdns.org`) && PathPrefix(`/h2-console`)"
      - "traefik.http.routers.backend-h2.entrypoints=websecure"
      - "traefik.http.routers.backend-h2.tls.certresolver=myresolver"
      - "traefik.http.services.backend-h2.loadbalancer.server.port=8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./data/tfg_backend:/app/data 
      - ./backend/uploads:/app/uploads
    networks:
      - tfg-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tfg-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`tfgproject.duckdns.org`) && (PathPrefix(`/`) && !PathPrefix(`/api`))"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
    networks:
      - tfg-network

networks:
  tfg-network:
